#!/bin/bash
#
# rundeckd    Startup script for the rundeck

# Source function library
. /lib/lsb/init-functions
. /etc/rundeck/profile

prog="rundeckd"
PIDFILE=/var/run/$prog.pid
DAEMON="${JAVA_HOME:-/usr}/bin/java"
DAEMON_ARGS="${RDECK_JVM} -cp ${BOOTSTRAP_CP} com.dtolabs.rundeck.RunServer /var/lib/rundeck 4440"
rundeckd="$DAEMON $DAEMON_ARGS"

function shutdown()
{
    echo -n "`date +"%d.%m.%Y %T.%3N"` - Stopping ${prog}"
    killproc -p $PIDFILE "$rundeckd"
}

echo -n "`date +"%d.%m.%Y %T.%3N"` - Starting ${prog}"
cd /var/log/rundeck
nohup su -s /bin/bash rundeck -c "$rundeckd &>>/var/log/rundeck/service.log" &
PID=$!
echo $PID > $PIDFILE

echo "==================================================================="
echo "config job snapshot instance"  >/var/log/rundeck/InstancesSnapshot.log


exec rd projects create -p InstancesSnapshot >>/var/log/rundeck/InstancesSnapshot.log

exec rd jobs load --file /opt/snapshot.xml --project InstancesSnapshot >>/var/log/rundeck/InstancesSnapshot.log"


echo "end job snapshot instance" >> /var/log/rundeck/InstancesSnapshot.log


trap shutdown HUP INT QUIT ABRT KILL ALRM TERM TSTP

while pgrep -F /var/run/rundeckd.pid > /dev/null; do sleep 5; done
