heat_template_version: 2013-05-23
parameters:
  network:
    label: network
    type: string
  subnet:
    label: subnet
    type: string
  cidr_net:
    label: subnet
    type: string
  os_type:
    label: os type
    type: string
  nodename:
    label: nodename
    type: string
  index:
    label: index
    type: string
  nodeip:
    label: nodeip
    type: string
  security_group:
    label: security_group
    type: string
  keypair_name:
    label: SSH Keypair
    type: string
  flavor_name:
    type: string
    label: Instance Type (Flavor)

resources:

  glusterfs_port:
      type: OS::Neutron::Port
      properties:
        network: { get_param: network }
        fixed_ips:
          - ip_address: { get_param: nodeip }
            subnet_id: { get_param: subnet }
        security_groups:
          - { get_param: security_group }

  node:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: keypair_name }
      name: {get_param: nodename }
      image: { get_param: os_type }
      flavor: { get_param: flavor_name }
      networks:
        - port: { get_resource: glusterfs_port }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
                  #!/bin/bash
                  mkdir /etc/ansible
                  echo "[local]" >> /etc/ansible/hosts
                  echo "127.0.0.1 ansible_connection=local" >> /etc/ansible/hosts
                    cat << EOF > /etc/ansible/vars.yml
                       gluster_mount_dir: /mnt/gluster
                       gluster_brick_dir: /srv/gluster/brick
                       gluster_brick_name: gluster
                       node:
                         0: $prefix_net0
                         1: $prefix_net1
                  EOF

                  if [ "$os" == "Debian Jessie" ] ;
                  then
                  /usr/local/bin/ansible-pull -U https://github.com/cloudwatt/applications.git blueprint-3tiers/ansible/glusterfs.yml -e @/etc/ansible/vars.yml
                  else
                  ansible-pull -U https://github.com/cloudwatt/applications.git blueprint-3tiers/ansible/glusterfs.yml -e @/etc/ansible/vars.yml
                  fi
          params:
                $os: { get_param: os_type }
                $prefix_net: { "Fn::Replace": [ {'.0/24': '.12'}, {get_param: cidr_net} ] }
