- hosts: local
  user: cloud
  sudo: true

  vars:
    pg_admin_pass: "{{ lookup('password', '/root/keystore chars=ascii_letters,digits,hexdigits,punctuation') }}"
    
  tasks:
    - name: volume is linked
      stat: path=/dev/vdb
      register: vol_link

    - name: data partition is ready
      stat: path=/dev/vdb1
      register: data_partition

    - name: setting fact
      set_fact: data_volume_ready="{{ vol_link.stat.exists and data_partition.stat.exists }}"

    - name: create partition
      shell: "{{ item }}"
      with_items:
        - /sbin/parted --script /dev/vdb -- mklabel msdos
        - /sbin/parted --script /dev/vdb -- mkpart primary 0% 100%
        - /sbin/mkfs.ext4 /dev/vdb1
      when: not data_volume_ready
      register: partition_creation

    - name: setting fact
      set_fact: data_volume_ready=true
      when: partition_creation|success

    - name: mountpoint ready
      file:
        path=/mnt/data
        state=directory
        owner=root
        group=root
        mode=0755

    - name: data is volume mounted
      mount:
        name=/mnt/data
        src=/dev/vdb1
        fstype=ext4
        state=mounted

    - name: postgresql data directory
      stat: path=/var/lib/postgresql/9.3/main
      register: data_dir

    - name: postgresql data directory
      stat: path=/var/lib/postgresql/9.3/main
      register: data_dir

    - name: service down
      service:
        name=postgresql
        state=stopped
      when: not data_dir.stat.islnk

    - name: move data
      shell: mv /var/lib/postgresql/9.3/main /mnt/data/pgsql_data
      when: not data_dir.stat.islnk

    - name: data link
      file:
        src=/mnt/data/pgsql_data
        dest=/var/lib/postgresql/9.3/main
        state=link

    - name: service up
      service:
        name=postgresql
        state=started
        enabled=yes

    - name: create admin user
      sudo_user: postgres
      postgresql_user:
        name=pgadmin
        state=present
        password="{{ pg_admin_pass }}"
