heat_template_version: 2013-05-23
description: AutoScaling blueprint exemple
parameters:
  keypair_name:
    description: Keypair to inject in instance
    default: alikey
    label: SSH Keypair
    type: string

  flavor_name:
    default: n2.cw.standard-1
    description: Flavor to use for the deployed instance
    type: string
    label: Instance Type (Flavor)
    constraints:
      - allowed_values:
          - t1.cw.tiny
          - s1.cw.small-1
          - n2.cw.standard-1
          - n2.cw.standard-2
          - n2.cw.standard-4
          - n2.cw.standard-8
          - n2.cw.standard-16
          - n2.cw.highmem-2
          - n2.cw.highmem-4
          - n2.cw.highmem-8
          - n2.cw.highmem-12
  net_cidr:
    default: 192.168.0.0/24
    description: /24 cidr of fronts network
    label: /24 cidr of fronts network
    type: string

  router:
    label: router
    type: string
    default: 3eb0ebb7-36ec-4846-b642-d20039e31ba6
  mcm_public_key:
    type: string
    label: mcm public key
    default: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3IeALS1ymhqkaLicduq4BADIKUPcd5P/SU2OCjUGYco4108aBzl+ZbWXhWnHxxhCXyWj1ka7X4UK63g1skCMw1FMLKxdFggfwnbwTOA2WufxFhnfAOG3IDWcwqPCCiYhutJo0231kmMrap9gb2uaWa3/ZR4O8ZXBBWugFQqBL3AFCdm07zOs/lPHS4Q/RrKejNrbqb3GSXyiDzR6PnDCxCSNJKoIj9Fh1if8gctpoiUOi4C7TqHqWWvJ2ctbFZpxxDvwaqI5HnJgfi0lU2goKvHOG02AnqHBU+N6Xh7Bt5f05bREUzwdeZK2XWmaVDsqleHkgxZ5GsQsDvWJR7UGj root@mcm-driver-0.novalocal


resources:

  net:
    type: OS::Neutron::Net
    properties:
      admin_state_up: true

  subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: net }
      cidr: { get_param: net_cidr }
      gateway_ip: { "Fn::Replace": [ {'.0/24': '.1'}, {get_param: net_cidr} ] }


  interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_param: router }
      subnet_id: { get_resource: subnet }

  sec_group:
    type: OS::Neutron::SecurityGroup
    properties:
      rules:
        - { direction: ingress, protocol: TCP }
        - { direction: ingress, protocol: UDP }
        - { direction: ingress, protocol: ICMP }
        - { direction: egress, protocol: ICMP }
        - { direction: egress, protocol: TCP }
        - { direction: egress, protocol: UDP }

  asg:
    type: OS::Heat::AutoScalingGroup
    properties:
      min_size: 2
      max_size: 6
      resource:
        type: lb_server.yaml
        properties:
          flavor: {get_param: flavor_name}
          image: Ubuntu 14.04
          key_name: {get_param: keypair_name}
          network: {get_resource: network}
          pool_id: {get_resource: pool}
          security_group: { get_resource: sec_group }


  web_server_scaleup_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: asg}
      cooldown: 60
      scaling_adjustment: 1
  web_server_scaledown_policy:
    type: OS::Heat::ScalingPolicy
    properties:
      adjustment_type: change_in_capacity
      auto_scaling_group_id: {get_resource: asg}
      cooldown: 60
      scaling_adjustment: -1

  pool:
    type: OS::Neutron::Pool
    properties:
      protocol: HTTP
      subnet_id: {get_resource: subnet}
      lb_method: ROUND_ROBIN
      vip:
        protocol_port: 80
  lb:
    type: OS::Neutron::LoadBalancer
    properties:
      protocol_port: 80
      pool_id: {get_resource: pool}

  # assign a floating ip address to the load balancer
  # pool.
  lb_floating:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network_id: 6ea98324-0f14-49f6-97c0-885d1b8dc517
      port_id: {get_attr: [pool, vip, port_id]}

outputs:
  scale_up_url:
    description: >
      This URL is the webhook to scale up the autoscaling group.  You
      can invoke the scale-up operation by doing an HTTP POST to this
      URL; no body nor extra headers are needed.
    value: {get_attr: [web_server_scaleup_policy, alarm_url]}
  scale_dn_url:
    description: >
      This URL is the webhook to scale down the autoscaling group.
      You can invoke the scale-down operation by doing an HTTP POST to
      this URL; no body nor extra headers are needed.
    value: {get_attr: [web_server_scaledown_policy, alarm_url]}
  pool_ip_address:
    value: {get_attr: [pool, vip, address]}
    description: The IP address of the load balancing pool
  website_url:
    value:
      str_replace:
        template: http://host/
        params:
          host: { get_attr: [lb_floating, floating_ip_address] }
    description: >
      This URL is the "external" URL that can be used to access the
      Wordpress site.
