heat_template_version: 2013-05-23
description: A load-balancer server
parameters:
  image:
    type: string
    description: Image used for servers
  key_name:
    type: string
    description: SSH key to connect to the servers
  flavor:
    type: string
    description: flavor used by the servers
  pool_id:
    type: string
    description: Pool to contact
  network:
    type: string
    description: Network used by the server
  security_group:
    label: security_group
    type: string  

resources:
  server:
    type: OS::Nova::Server
    properties:
      flavor: {get_param: flavor}
      image: {get_param: image}
      key_name: {get_param: key_name}
      name:
         str_replace:
               template: $stack
               params:
                  $stack: { get_param: 'OS::stack_name' }
      networks: [{network: {get_param: network} }]
      security_groups:
        - { get_param: security_group }
      user_data_format: RAW
      user_data: 
         str_replace:
             template: |
               #!/bin/bash
               sudo apt-get -y update
               sudo apt-get install -y apache2
             params:
                 $flavor: { get_param: flavor }  
         
  member:
    type: OS::Neutron::PoolMember
    properties:
      pool_id: {get_param: pool_id}
      address: {get_attr: [server, first_address]}
      protocol_port: 80

outputs:
  server_ip:
    description: IP Address of the load-balanced server.
    value: { get_attr: [server, first_address] }
  lb_member:
    description: LB member details.
    value: { get_attr: [member, show] }
