---
#
##
### Written by the CAT (Cloudwatt Automation Team)
##
#
- hosts: local
  user: cloud
  become: yes

  tasks:

    - apt: update_cache=true upgrade=full

    - name: install packages
      apt: pkg={{ item }} state=present
      with_items:
        - zabbix-agent
        - ntp

    - name: get zabbix_server IP
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp=".*Server=.*"
        line="Server=10.0.7.100"

    - name: zabbix slave hostname
      lineinfile:
        name=/etc/zabbix/zabbix_agentd.conf
        regexp="^Hostname="
        line="Hostname={{ ansible_hostname }}"
      notify: restart zabbix

    - name: register zabbix agent
      local_action:
          module: zabbix_host
          server_url: "http://84.39.40.231/"
          login_user: "admin"
          login_password: "zabbix"
          host_name: "{{ ansible_hostname }}"
          link_templates:
             - Template Autoscaling
          host_groups:
             - Linux servers
          status: enabled
          state: present
          interfaces:
            - type: 1
              main: 1
              useip: 1
              ip: "{{ ansible_default_ipv4.address }}"
              dns: "{{ ansible_hostname }}"
              port: 10050



  handlers:
    - name: restart ntp
      service:
        name=ntp
        state=restarted
        enabled=yes

    - name: restart zabbix
      service:
        name=zabbix-agent
        state=restarted
        enabled=yes